# Generated by Django 3.0.4 on 2020-03-09 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoNombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partecuerpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CuerpoNombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detallecuerpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.Estado')),
                ('partecuerpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.Partecuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='Demonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DemonioNombre', models.CharField(max_length=50)),
                ('detallecuerpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.Detallecuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.Demonio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.Estado')),
            ],
        ),
    ]
