# Generated by Django 3.0.4 on 2020-03-10 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0002_auto_20200309_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demonio',
            name='estado',
        ),
        migrations.AddField(
            model_name='demonio',
            name='detallecuerpo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estado.Detallecuerpo'),
            preserve_default=False,
        ),
    ]
